---
title: "predicting_gold_presence"
author: "Matt Twigg"
date: "7/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Introduction  

I will predict gold presence from other minerals

```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(corrplot)
library(factoextra)
```

```{r}
dn <- read.csv("deadwoodnorth.csv")
ds <- read.csv("deadwoodsouth.csv")
ld <- read.csv("lead.csv")
tn <- read_csv("tinton.csv")
sp <- read_csv("spearfish.csv")
```



```{r}
sites <- rbind(dn, ds, ld, tn, sp)
sites
```




```{r}
s1 <- sites %>% select(
  dep_id,
  site_name,
  latitude,
  longitude,
  commod1,
  commod2,
  commod3,
)
```


```{r}
s2 <- data.frame(s1)
```


```{r}
s2$commod2 <- as.factor(s2$commod2)
```

```{r}
str(s2)
```
```{r}
s2com <- unite(s2, commodities, 5:7, sep = ", ")
str(s2com)
```

```{r}
au <- str_detect(s2com$commodities, "Gold")
#au
```

```{r}
s2com1 <- cbind(s2com, au)
```

```{r}
reds2com <- subset(s2com1, au == TRUE)
```

```{r}
reds2comF <- subset(s2com1, au == FALSE)
```

```{r}
reds <- rbind(reds2com, reds2comF)
reds
```


```{r}
rownames(reds) <- 1:nrow(reds)
#reds2com
```


```{r}
colreds <- reds %>% separate(commodities, c("one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen"), "," ) 
```
```{r}
colSums(is.na(colreds))
```
```{r}
reducedcol <- colreds %>% select(1:15)
```

```{r}
colSums(is.na(reducedcol))
```
```{r}
reducedcol
```


```{r}
noNA <- reducedcol %>% replace_na(list(four = "", five = "", six  = "", seven  = "", eight  = "", nine = "", ten  = "", eleven  = ""))
noNA[noNA == " NA"] <- ""
write.csv(noNA, file = "noNA2full.csv")
#View(noNA)
noNA
```


```{r}
outFull <- unite(noNA, commodities, 5:15, sep = ", ")
#write.csv(outFull, file = "outFull2.csv")
#outFull
```




```{r}
imported <- read.csv("inFull2.csv")
imported
```

```{r}
str(imported)
```


```{r}
minerals <- c(colnames(imported[7:38]))
mined <- integer()
#count <- 0
for (names in minerals){
  mined <- c(mined, sum(imported[[names]]))
}
mined
```
```{r}
minerals
```
```{r}
bonded <- rbind(minerals, mined)
bonded
```


```{r}
totals <- data.frame(minerals, mined)
totals
```



```{r}
htot <- as.data.frame(t(totals$mined))
colnames(htot) <- minerals
htot
```

## Visualizations 

```{r}
barplot(totals$mined)
```


```{r}
str(imported)
```


```{r}
corrdf <- imported %>% select(
  7:38
)
corrdf
```

```{r}
corrdfvalues <- cor(corrdf)
```


```{r}
corrplot(corrdfvalues)
```




```{r}
#write.csv(corrdf, file = "corrdf.csv")
factCorr <- read_csv("factoredCorrdf.csv")
factCorr
```



```{r}
set.seed(123)
km.res <- kmeans(corrdf, 5, nstart = 25)
km.res$cluster
```

```{r}
#View(corrdf)
result  <- kmeans(corrdf, 5)
fviz_cluster(result, data = corrdf)
```






```{r}
mineralsAuAgPb <- lm(Gold ~ Silver + Lead, data = factCorr) 
mineralsAuAgPb
```
```{r}
summary(mineralsAuAgPb)
```
```{r}
anova(mineralsAuAgPb)
```


```{r}
plot(mineralsAuAgPb)
```
```{r}
coef(mineralsAuAgPb)
```


PCA#########################################################################
```{r}
pca <-prcomp(t(corrdf), scale. = TRUE)
plot(pca$x[,1], pca$x[,3])
rpca <- t(corrdf)
```
```{r}
# from https://www.google.com/search?client=firefox-b-1-e&q=principle+component+analysis+in+r#kpvalbx=_rN4qX7nDEtGF9PwP3vO4oAM88
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per, main = "Min Plot", xlab = "Principle Component", ylab = "Percent Variation")

```
```{r}
#rpca <t(pca$x)
#View(pca)
```


```{r}

pca.data <- data.frame(Sample=rownames(pca$x),
                       X=pca$x[,1],
                       Y=pca$x[,2])

pca.data
#View(pca.data)
```


```{r}
ggplot(data=pca.data, aes(x=X, y=Y, label=Sample))+
  geom_text()+
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep = ""))+
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep = ""))+
  theme_bw()+
  ggtitle("My Mineral Graph")
```
```{r}
#pca$rotation[,1]
```


```{r}
loading_scores <- pca$rotation[,1]
gene_scores <- abs(loading_scores)
gene_scores_ranked <- sort(gene_scores, decreasing = TRUE)
gene_scores_ranked
#top_10_genes <- names(gene_scores_ranked[1:10])
#top_10_genes
```

```{r}
pca$rotation[top_10_genes,1]
```




#####################################################################################




Goodness of fit?






